### ISSUE TITLE
[Bug]: lowcoder Image downloaded through Docker Desktop can run but localhost:3000 says ERR_CONNECTION_REFUSED (Windows)

### ISSUE THREAD

**Issue by Kenneth769** [lowcoder-org/lowcoder#1164] opened 2024-09-14 15:59 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi, I am quite new to this all coming from a more research background but your project seems very interesting and will help me a lot. Will be great if you can help see if this docker desktop image issue is more of my own problem and I need to go back to first command line using docker compose like in your instructions or not.

Just running the image with no other optional parameters
Image: lowcoder-ce:latest
The container is running fine it seems (not seeing any errors)
![image](https://github.com/user-attachments/assets/ecce603a-d6ce-4ff1-89de-3f86ec2f5244)

But nothing is taking the space of port 3000
![image](https://github.com/user-attachments/assets/667d139a-8b00-4336-b2ad-1058ea856c10)

![image](https://github.com/user-attachments/assets/508f6a99-09ff-4ac5-9ef3-b15190378cea)

### Expected Behavior

expecting localhost;3000 to show the UI

### Steps to reproduce

download Docker Desktop from docker
download lowcoer-ce image from docker desktop searchbar at the top

### Environment

Docker Desktop 4.34.2 (167172) is currently the newest version available.
Windows 10 Home

**Comment by FalkWolsky** [comment] 2024-09-16 20:10
When you use Docker Compose, you would need to set the port as "exposed Port". Cause - currently as by your setup, lowcoder is only to reach "inside Docker" (in the own docker system network).

In the "run" command it is already to see like this: 
`docker run -d --name lowcoder -p 3000:3000 -v "$PWD/stacks:/lowcoder-stacks" lowcoderorg/lowcoder-ce`

But in Docker Desktop, you do this "visually"

<img width="588" alt="Screenshot 2024-09-16 at 22 07 36" src="https://github.com/user-attachments/assets/a0771dee-af38-41ca-98ff-5517030d7f51">

You can see when you "run" an image - this configuration screen. You see there the 3 ports.
For your start, at least 3000 must be set as Port, so you can reach the UI of Lowcoder on your Desktop.

It is also truly suggested to make use of "/lowcoder-stacks" as Volume -> Container Path (as Host path you choose some folder on your computer) 

We will update our docs - but also close this issue - since it is not a bug. 

If you find still problems, it is suggested to visit our Discord Server and have the conversation there in the support forum.
https://discord.gg/An6PgWpegg

**Closed by FalkWolsky** 2024-09-16 20:10 UTC

**Comment by Kenneth769** [comment] 2024-09-17 10:17
Thanks, so the missing piece really is just the -p 3000:3000, care to explain what "/lowcoder-stacks" is and does please?
