### ISSUE TITLE
[Bug]: Table Component: Column gets hidden when Auto Width set to Auto

### ISSUE THREAD

**Issue by yogeshvachhani** [lowcoder-org/lowcoder#925] opened 2024-06-01 12:02 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The column stops showing.

### Expected Behavior

The column should automatically get adjusted and should be visible.

### Steps to reproduce

Place Table component on page.
Open options of any column and sets its Auto Width to Auto

### Additional Information

The product shows up when app is previewed.

**Comment by raheeliftikhar5** [comment] 2024-06-13 06:58
@yogeshvachhani I have tried reproducing this but failed. Normally when i set auto width for a column it has a min-width. Can you share more details so that i can reproduce this issue? Thanks

**Comment by yogeshvachhani** [comment] 2024-06-14 07:27
The problem is still there. It seems to work with static data but not when connected to a Query.

Here are screenshots for your reference.
![image](https://github.com/lowcoder-org/lowcoder/assets/109499572/3f255c3e-7708-4195-a7eb-8023ff60cc8c)

![image](https://github.com/lowcoder-org/lowcoder/assets/109499572/22536815-7e78-40a7-9f36-66bcaabf75a0)

**Comment by yogeshvachhani** [comment] 2024-06-14 07:30
If the number of columns fit in given table width then the column is visible.
![image](https://github.com/lowcoder-org/lowcoder/assets/109499572/acbd3ddd-144b-47ce-b886-75236e37f5aa)

**Comment by yogeshvachhani** [comment] 2024-06-14 07:33
Here second (Title) and third (Description) columns are set to Auto.
![image](https://github.com/lowcoder-org/lowcoder/assets/109499572/37f2dbb5-58f9-4265-b6fd-2292e6c30cc7)

**Comment by raheeliftikhar5** [comment] 2024-06-14 11:02
@yogeshvachhani Thank you for the details. Can you share which version of Lowcoder you are using?

**Comment by raheeliftikhar5** [comment] 2024-06-14 15:09
Also it will be helpful if you share a sample app.

**Comment by yogeshvachhani** [comment] 2024-06-15 04:54
> @yogeshvachhani Thank you for the details. Can you share which version of Lowcoder you are using?

I am using the version at https://app.lowcoder.cloud/.

It is 2.4.0.

**Comment by yogeshvachhani** [comment] 2024-06-15 04:56
> Also it will be helpful if you share a sample app.
[SampleTableApp.json](https://github.com/user-attachments/files/15845739/SampleTableApp.json)

**Comment by adnanqaops** [comment] 2024-09-10 08:29
In our environment ( both Local and Prod ) , we could not reproduce the issue and will close the issue therefore.
If you find the bug still persist - please re-open, so we can dig deeper where the problem may occur.

**Closed by adnanqaops** 2024-09-10 08:29 UTC
Labels: Javascript Frontend, Components
